package it.ats.hibernate;
// Generated Apr 5, 2019 12:53:10 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Contocorrente generated by hbm2java
 */
public class Contocorrente implements java.io.Serializable {

	private int idConto;
	private Integer numero;
	private Date dataApertura;
	private Date dataChiusura;
	private Double saldo;
	private Set utentiAssociazioneContos = new HashSet(0);

	public Contocorrente() {
	}

	public Contocorrente(int idConto) {
		this.idConto = idConto;
	}

	/**
	 * Constructor
	 * @param idConto
	 * @param numero
	 * @param dataApertura
	 * @param dataChiusura
	 * @param saldo
	 * @param utentiAssociazioneContos
	 */
	public Contocorrente(int idConto, Integer numero, Date dataApertura, Date dataChiusura, Double saldo,
			Set utentiAssociazioneContos) {
		this.idConto = idConto;
		this.numero = numero;
		this.dataApertura = dataApertura;
		this.dataChiusura = dataChiusura;
		this.saldo = saldo;
		this.utentiAssociazioneContos = utentiAssociazioneContos;
	}

	/**
	 * Per accedere alle variabili dichiarate private sono stati definiti 
	 * i metodi getter e setter 
	 * @return idConto, numero, dataApertura, dataChiusura, saldo e 
	 * utentiAssociazioneConto
	 */
	public int getIdConto() {
		return this.idConto;
	}

	public void setIdConto(int idConto) {
		this.idConto = idConto;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Date getDataApertura() {
		return this.dataApertura;
	}

	public void setDataApertura(Date dataApertura) {
		this.dataApertura = dataApertura;
	}

	public Date getDataChiusura() {
		return this.dataChiusura;
	}

	public void setDataChiusura(Date dataChiusura) {
		this.dataChiusura = dataChiusura;
	}

	public Double getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	public Set getUtentiAssociazioneContos() {
		return this.utentiAssociazioneContos;
	}

	public void setUtentiAssociazioneContos(Set utentiAssociazioneContos) {
		this.utentiAssociazioneContos = utentiAssociazioneContos;
	}

}
