package it.ats.hibernate;
// Generated Apr 5, 2019 12:53:10 PM by Hibernate Tools 5.1.10.Final

/**
 * UtentiAssociazioneContoId generated by hbm2java
 */
public class UtentiAssociazioneContoId implements java.io.Serializable {

	private int ndg;
	private int idConto;

	/**
	 * Constructor
	 */
	public UtentiAssociazioneContoId() {
	}

	/**
	 * 
	 * @param ndg
	 * @param idConto
	 */
	public UtentiAssociazioneContoId(int ndg, int idConto) {
		this.ndg = ndg;
		this.idConto = idConto;
	}

	public int getNdg() {
		return this.ndg;
	}

	public void setNdg(int ndg) {
		this.ndg = ndg;
	}

	public int getIdConto() {
		return this.idConto;
	}

	public void setIdConto(int idConto) {
		this.idConto = idConto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtentiAssociazioneContoId))
			return false;
		UtentiAssociazioneContoId castOther = (UtentiAssociazioneContoId) other;

		return (this.getNdg() == castOther.getNdg()) && (this.getIdConto() == castOther.getIdConto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNdg();
		result = 37 * result + this.getIdConto();
		return result;
	}

}
