package it.ats.hibernate;
// Generated Apr 5, 2019 12:53:10 PM by Hibernate Tools 5.1.10.Final

/**
 * UtentiAssociazioneConto generated by hbm2java
 */
public class UtentiAssociazioneConto implements java.io.Serializable {

	private UtentiAssociazioneContoId id;
	private Contocorrente contocorrente;
	private Utenti utenti;

	public UtentiAssociazioneConto() {
	}

	public UtentiAssociazioneConto(UtentiAssociazioneContoId id, Contocorrente contocorrente, Utenti utenti) {
		this.id = id;
		this.contocorrente = contocorrente;
		this.utenti = utenti;
	}

	public UtentiAssociazioneContoId getId() {
		return this.id;
	}

	public void setId(UtentiAssociazioneContoId id) {
		this.id = id;
	}

	public Contocorrente getContocorrente() {
		return this.contocorrente;
	}

	public void setContocorrente(Contocorrente contocorrente) {
		this.contocorrente = contocorrente;
	}

	public Utenti getUtenti() {
		return this.utenti;
	}

	public void setUtenti(Utenti utenti) {
		this.utenti = utenti;
	}

}
